title: J.P. Meagher
author: J.P. Meagher
email: joe.meagher@ucd.ie
description: > # this means to ignore newlines until "baseurl:"
  J.P. Meagher \\
  Post-doctoral Researcher \\
  The Insight Centre for Data Analytics \\
  University College Dublin \\
# social links
twitter_username: jp_meagher # DO NOT include the @ character, or else the build will fail!
github_username:  jpmeagher # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate
